# Generated by Django 5.2 on 2025-05-02 14:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournifyx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='category',
            field=models.CharField(choices=[('sports', 'Sports'), ('esports', 'Esports'), ('quiz', 'Quiz')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
