# Generated by Django 5.2 on 2025-05-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournifyx', '0005_alter_player_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='category',
            field=models.CharField(choices=[('valorant', 'Valorant'), ('football', 'Football'), ('cricket', 'Cricket'), ('chess', 'Chess')], default='valorant', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='num_participants',
            field=models.PositiveIntegerField(),
        ),
    ]
