# Generated by Django 5.2 on 2025-08-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournifyx', '0006_remove_tournament_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='match_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='num_participants',
            field=models.IntegerField(default=0),
        ),
    ]
