# Generated by Django 5.2 on 2025-08-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournifyx', '0008_tournament_is_paid_tournament_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='category',
            field=models.CharField(choices=[('football', 'Football'), ('cricket', 'Cricket'), ('basketball', 'Basketball')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='match_type',
            field=models.CharField(choices=[('knockout', 'Knockout'), ('league', 'League')], max_length=50),
        ),
    ]
