# Generated by Django 5.2 on 2025-08-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournifyx', '0009_alter_tournament_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='category',
            field=models.CharField(choices=[('football', 'Football'), ('valorant', 'Valorant'), ('cricket', 'Cricket'), ('basketball', 'Basketball')], max_length=50),
        ),
    ]
