# Generated by Django 5.2 on 2025-09-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournifyx', '0010_alter_tournament_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
