# Generated by Django 5.2 on 2025-09-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournifyx', '0013_pointtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
