# Generated by Django 5.2 on 2025-09-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournifyx', '0014_alter_match_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_draw',
            field=models.BooleanField(default=False),
        ),
    ]
