# Generated by Django 5.2 on 2025-10-09 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournifyx', '0016_match_round_number_alter_match_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='parent_match1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_parent1', to='tournifyx.match'),
        ),
        migrations.AddField(
            model_name='match',
            name='parent_match2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_parent2', to='tournifyx.match'),
        ),
    ]
