# Generated by Django 5.2 on 2025-10-09 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournifyx', '0018_match_needs_confirmation_matchchangelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='needs_confirmation',
        ),
        migrations.DeleteModel(
            name='MatchChangeLog',
        ),
    ]
