# Generated by Django 5.2 on 2025-10-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournifyx', '0024_leaverequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='contact_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
